name: proyectoedumentor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+14

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  provider: ^6.1.1
  shared_preferences: ^2.3.2
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  http: ^1.2.1
  url_launcher: ^6.3.0
  intl: any
  crypto: ^3.0.5
  open_file: ^3.3.2
  file_picker: ^8.1.2
  path: ^1.8.3
  path_provider: ^2.1.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/
    - assets/icon/google.png